alias ls='ls -lht'
alias tpt='trash-put'
alias trm='trash-rm'
alias rm='echo "This is not the command you are looking for.  Use 'trash-put' ('tpt') or 'trash-rm' ('trm') instead"'
alias delete-file='\rm'
